config/routes.rb
Rails.application.routes.draw do

  # get 'achievements/index'
  # get 'achievements/show'
  # get 'achievements/new'
  # get 'achievements/edit'
  # root to: "homes#index"

 resources :homes
 resources :achievements
 devise_for :users
#  get "/home", to:"home#index"
root "homes#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/achievement.rb
class Achievement < ApplicationRecord
    belongs_to :user
   has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :achievements 
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  
  def index 
    @achievements = current_user.achievements
  end 

  def show 
    @achievement = current_user.achievements.find(params[:id])
    # @image =  @achievement.image.attach(params[:image])
  end 
  

 def new 
  @achievement = current_user.achievements.new 
 end 

 def create 
  current_user.achievements.create(achievements_params)
  redirect_to achievements_path
 end 

def edit 
  @achievement = current_user.achievements.find(params[:id])
end 


def update
  @achievement= current_user.achievements.find(params[:id])
  @achievement.update(achievements_params)
  

  redirect_to achievements_path

end 
 def destroy 
  
  @achievement=current_user.achievements.find(params[:id])
  @achievement.destroy
  redirect_to achievements_path
 end 


 def achievements_params 
   params.require(:achievement).permit(:achievement, :note, :date, :image)
 end 
  
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :authenticate_user!
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @achievements = Achievement.all
  end



end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/achievements/edit.html.erb
<h1>Achievements#edit</h1>
<p>Find me in app/views/achievements/edit.html.erb</p>

<%= form_for @achievement, url: {action: "update"} do |f|%>
    



    <div class="field">
    <%= f.label :achievement%> <br />
    <%= f.text_field :achievement , :required=> true%>
  </div>
  
       <div class="field">
         <%= f.label :note%><br />
         <%= f.text_field :note, :required=> true %>
       </div>
      
       <div class="field">
         <%= f.label :date %><br />
         <%= f.date_field :date , :required=> true %> 
       </div>
       <div class="field">
         <%= f.label :image %><br />
         <%= f.file_field :image, :required=> true %>
       </div>
      
       <div class="actions">
         <%= f.submit "update" %>
       </div>
      <% end %> 
  

app/views/achievements/index.html.erb
<h1> Your Achievements</h1> 

<div class="card-design">
<% @achievements.each  do |achievement|%>
    <div class="card mb-3 card-width" >
    <div class="row no-gutters">
      <div class="col-md-4">
      <% if achievement.image.attached? %>
            <img src= "<%=(url_for(achievement.image))%>" class="img-size card-img" > 
        <% end %> 
        </div>
    
        <div class="col-md-8 text-card">
        <div class="card-body">
          <h5 class="card-title">   <%=achievement.achievement%>
        </h5>
   
 
    
    <p class="card-text"><%=achievement.note%></p>

    <p class="card-text"><small class="text-muted"><%=achievement.date%> </small></p>

   
    <%= link_to "Show ", achievement_path(achievement), class: "btn btn-primary btn-md btn-block" %>

    </div>
    </div>
</div>
</div>
<%end%>


</div>  
        
      

app/views/achievements/new.html.erb
<h1>I'm so proud that you accomplished one of your goals</h1>


<%= form_for @achievement, url: {action: "create"} do |f|%>
    



  <div class="field">
  <%= f.label :achievement%> <br />
  <%= f.text_field :achievement , :required => true %>
</div>

     <div class="field">
       <%= f.label :note%><br />
       <%= f.text_field :note ,:required=> true %>
     </div>
    
     <div class="field">
       <%= f.label :date %><br />
       <%= f.date_field :date  ,:required=> true %> 
     </div>
     <div class="field">
       <%= f.label :image %><br />
       <%= f.file_field :image ,:required=> true%>
     </div>
    
     <div class="actions">
       <%= f.submit "Save" %>
     </div>
    <% end %> 

app/views/achievements/show.html.erb
<h1> your Achievement</h1>

<% if @achievement.image.attached? %>
<img src= "<%=(url_for(@achievement.image))%>" class="img-size"> 
<% end %> 
<p>
<%=@achievement.achievement%>  
<br>
<%=@achievement.note%>
<br>
<%=@achievement.date%>  
</p> 
<br>
<%=link_to "Edit" ,edit_achievement_path%>
<%=link_to "Delete", achievement_path(@achievement), method: :delete%>
 

app/views/homes/edit.html.erb
<h1>Homes#edit</h1>
<p>Find me in app/views/homes/edit.html.erb</p>

app/views/homes/index.html.erb
<h1>I'm so proud that you accomplished one of your goals </h1>

 <h2> Here start your journey in the world of success start writing your Achievements  
  </h2>


    <video style ="float:right; margin-right:10px "width="550" height="550;" autoplay controls >
    <source src="<%=asset_path('video.mp4')%>" type="video/mp4">
    <source src="<%=asset_path('video.mp4')%>">
    Your browser does not support the video tag.
    </video>

app/views/homes/new.html.erb
<h1>Homes#new</h1>
<p>Find me in app/views/homes/new.html.erb</p>

app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Achievements</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">

 
  <nav class="nav nav-container">
  <div>

      <h1>World of Achievements  </h1> 
      </div>
      <div>
  <%if user_signed_in? %>
  
    <%=link_to "Home " , homes_path%> 
    <%= link_to "sign out" , destroy_user_session_path , method: :delete%> 
      
      <%= link_to "My Achievment" ,achievements_path %>
      <%= link_to "Add Achievment " ,new_achievement_path%>
      <%else%>
      <%= link_to "Login", new_user_session_path%>
      <%= link_to "sign up" ,new_user_registration_path %> 
  <%end%>
  </div>
  </nav>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
 
  </body>
</html>



 